---
dependencies:
  - bootstrap
  - { role: neo-battery-tools, when: '"NanoPi NEO" in machine_type.stdout' }
  - dns-dhcp
  - network-interfaces
  - wifi-ap
  - mikegleasonjr.firewall
  - nginx
  - webserver-content
  - usb-content
  - sample-content
