language: bash
sudo: required
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_22a22c63eb0e_key -iv $encrypted_22a22c63eb0e_iv
  -in ci/travis-ci-biblebox.pem.enc -out ci/travis-ci-biblebox.pem -d
- sudo apt-get -qq update
install:
- wget -O /tmp/vagrant.deb https://releases.hashicorp.com/vagrant/1.8.7/vagrant_1.8.7_x86_64.deb
- sudo dpkg -i /tmp/vagrant.deb
- vagrant plugin install vagrant-aws
- vagrant plugin list
- vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
- sudo pip install -r requirements.txt
script:
- pwd
- ansible-lint -x ANSIBLE0004,ANSIBLE0012 --exclude=ansible/roles/mikegleasonjr.firewall
  --exclude=ansible/roles/geerlingguy.nginx ansible/site.yml
- cd ansible; pwd
- pwd
