language: bash
sudo: required
install:
- sudo apt-get install vagrant
- sudo -H pip install -r requirements.txt
script:
- ansible-lint -x ANSIBLE0004,ANSIBLE0012 --exclude=ansible/roles/mikegleasonjr.firewall --exclude=ansible/roles/geerlingguy.nginx ansible/site.yml
