language: bash
sudo: required
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_22a22c63eb0e_key -iv $encrypted_22a22c63eb0e_iv
  -in ci/travis-ci-biblebox.pem.enc -out ci/travis-ci-biblebox.pem -d
- sudo apt-get -qq update
install:
- sudo apt-get install vagrant
- sudo apt-get install build-essential libxslt-dev libxml2-dev zlib1g-dev ruby-dev
- sudo pip install -r requirements.txt
- gem install vagrant-aws
- ls -l `gem env gemdir`/cache/vagrant-aws*.gem
- vagrant plugin list
- pushd `gem env gemdir`/cache && vagrant plugin install vagrant-aws-0.7.2.gem && popd
- vagrant plugin list
script:
- ansible-lint -x ANSIBLE0004,ANSIBLE0012 --exclude=ansible/roles/mikegleasonjr.firewall
  --exclude=ansible/roles/geerlingguy.nginx ansible/site.yml
