language: bash
sudo: required
# Need trusty for a recent-ish version of vagrant
dist: trusty
before_install:
  - sudo apt-get -qq update
install:
- sudo apt-get install vagrant
- sudo apt-get install build-essential libxslt-dev libxml2-dev zlib1g-dev
- sudo pip install -r requirements.txt
- gem install --verbose vagrant-aws
- gem env gemdir
- find / -name "*.gem"
- vagrant plugin install `gem env gemdir`/cache/*/vagrant-aws*.gem
- vagrant plugin list
script:
- ansible-lint -x ANSIBLE0004,ANSIBLE0012 --exclude=ansible/roles/mikegleasonjr.firewall --exclude=ansible/roles/geerlingguy.nginx ansible/site.yml
