---
- name: restart pa6 pulldown service
  systemd:
    name: "{{ pa6_pulldown_enabler_service_name }}"
    daemon_reload: yes
    state: restarted

- name: restart neo battery shutdown service
  systemd:
    name: "{{ battery_tool_service_name }}"
    daemon_reload: yes
    state: restarted

