---
- name: Stop NetworkManager
  service: name=network-manager state=stopped enabled=no

- name: Remove NetworkManager
  apt: pkg=network-manager
       state=absent

- name: Configure network interfaces
  template:
    src: etc_network_interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify: Restart network
