---
- name: Set correct arguments for mounting USB drives
  copy:
    src: etc_udev_rules.d_automount.rules
    dest: /etc/udev/rules.d/automount.rules
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload udev rules
    - Warn to remount USB
