---
- name: Install usbmount for auto mounting of USB drives
  apt:
    name: usbmount
    state: present

- name: Expose usb content to the webserver
  file:
    src: /media/usb0
    dest: "{{ biblebox_usb_files_root }}"
    state: link

- name: modify usbmount to mount as www-data
  lineinfile:
    dest: /etc/usbmount/usbmount.conf
    regexp: 'FS_MOUNTOPTIONS=""'
    line: 'FS_MOUNTOPTIONS="-fstype=vfat,gid=www-data,uid=www-data"'
