---
- name: Create mount point for first USB drive
  file:
    path: "{{ connectbox_usb_files_root }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set correct arguments for mounting USB drives
  copy:
    src: etc_udev_rules.d_automount.rules
    dest: /etc/udev/rules.d/automount.rules
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload udev rules
    - Warn to remount USB

- name: Teach systemd-udev to expose mount points to the system
  lineinfile:
    path: /lib/systemd/system/systemd-udevd.service
    regexp: '^MountFlags='
    line: 'MountFlags=shared'
  notify:
    - Reload systemd-udevd unit file and restart service
