---
- name: Install hostapd
  apt:
    name: hostapd
    state: present

- name: Copy hostapd config
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0644
  register: etc_hostapd_hostapd_conf

- name: Copy script to set regulatory domain
  template:
    src: set_wifi_country_code.sh.j2
    dest: /etc/hostapd/set_wifi_country_code.sh
    owner: root
    group: root
    mode: 0755

- name: Populate /etc/default/crda with regulatory domain override
  template:
    src: etc_default_crda.j2
    dest: /etc/default/crda
    owner: root
    group: root
    mode: 0644

# We're using the ifupdown method instead of the initscript method
#  so this is just an ifdown and ifup operation rather than a
#  service reload hostapd
# Note: this is not a handler because wlan0/hostapd might be broken in later steps
# before the handler would be executed. This ensures that wlan0 will be up and
# hostapd properly running before exiting this role.
- name: Reload hostapd
  shell: "ifdown wlan0; sleep 1; ifup wlan0"
  when: etc_hostapd_hostapd_conf.changed
  tags:
    # This task on change is intentionally not a handler; don't trigger ANSIBLE0016
    - skip_ansible_lint

