---
- name: Install hostapd
  apt:
    name: hostapd
    state: present

- name: Copy hostapd config
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0644

- name: Start and enable hostapd
  service:
    name: hostapd
    enabled: yes
    state: started
