---
- name: Install hostapd
  apt:
    name: hostapd
    state: present

- name: Copy hostapd config
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0644
  register: etc_hostapd_hostapd_conf

# We're using the ifupdown method instead of the initscript method
#  so this is just an ifdown and ifup operation rather than a
#  service reload hostapd
- name: Reload hostapd
  shell: "ifdown wlan0; sleep 1; ifup wlan0"
  when: etc_hostapd_hostapd_conf.changed
  tags:
    # This task on change is intentionally not a handler; don't trigger ANSIBLE0016
    - skip_ansible_lint

