---
# No need to start this service given it's an at-boot one-shot
# Must do a daemon reload so that systemd knows about this new service
- name: Enable connectbox sshswitch service
  systemd:
    name: connectbox-sshswitch.service
    enabled: yes
    daemon_reload: yes


# Skip lint because there's no way that ansible-lint can know at build time
#  that we're legitimately use shell because of the && that is always
#  present when this is run.
- name: Run final disabling commands
  shell: "'{{ final_command | quote }}'"
  args:
    warn: no
  when: final_command != ""
  tags:
  - skip_ansible_lint
