---
# Openresolv, by default, wants to update /etc/resolv.conf to use dnsmasq
#  as a local resolver. We stop it from doing that with resolvconf=NO
# If 127.0.0.1 is a system resolver when dnsmasq is running, all on-box
#  queries are answered with the local client-facing ip address. This breaks
#  apt updates and other stuff that needs a working resolver. This means that
#  clients get different results to their DNS queries (which are served
#  from dnsmasq) from queries run on-box i.e. using system resolver
#
#  This does not work with the openresolv that ships with raspbian-lite
#   based on jessie, which is why we need to upgrade it below
- name: Tell openresolv not to touch /etc/resolv.conf
  lineinfile:
    dest: /etc/resolvconf.conf
    line: resolvconf=NO
    state: present
  register: resolvconf_conf_changed

- name: Upgrade openresolv to a version that supports resolvconf=NO
  apt:
    name: openresolv
    state: latest
    default_release: jessie-backports

# This can't be a handler, as we need this config to be in place when
#  we install and start dnsmasq. If it is not, then openresolv removes
#  the entries in /etc/resolv.conf and breaks DNS
- name: Reload openresolv with config
  command: /sbin/resolvconf -u
  when: resolvconf_conf_changed.changed
  tags:
  - skip_ansible_lint

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Copy dnsmasq configuration
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
    validate: dnsmasq --test --conf-file=%s
  notify: Reload dnsmasq

# This is necessary because nginx redirects to the hostname, but the hostname
#  is listed in /etc/hosts and associated with 127.0.0.1 (so dnsmasq uses it
#  when answering queries). By adding this, and the localise-queries option
#  to dnsmasq, we answer with the address of the wifi interface. There's no
#  need to do this for the ethernet interface, as we're not answering queries
#  on that interface (we're not even listening)
- name: Add /etc/hosts entry for wifi interface
  lineinfile:
    dest: /etc/hosts
    line: "{{ client_facing_if_ip_address }} {{ biblebox_default_hostname }}"

- name: Start and enable dnsmasq
  service:
    name: dnsmasq
    enabled: yes
    state: started
