---
# Openresolv, by default, wants to update /etc/resolv.conf to use dnsmasq
#  as a local resolver. We stop it from doing that with resolvconf=NO
# If 127.0.0.1 is a system resolver when dnsmasq is running, all on-box
#  queries are answered with the local wlan ip address. This breaks apt
#  updates and other stuff that needs a working resolver. This means that
#  clients get different results to their DNS queries (which are served
#  from dnsmasq) from queries run on-box i.e. using system resolver
- name: Tell openresolv not to touch /etc/resolv.conf
  lineinfile:
    dest: /etc/resolvconf.conf
    line: resolvconf=NO
    state: present
  register: resolvconf_conf_changed

# This can't be a handler, as we need this config to be in place when
#  we install and start dnsmasq. If it is not, then openresolv removes
#  the entries in /etc/resolv.conf and breaks DNS
- name: Reload openresolv with config
  command: /sbin/resolvconf -u
  when: resolvconf_conf_changed

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Copy dnsmasq configuration
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
    validate: dnsmasq --test --conf-file=%s
  notify: Reload dnsmasq

- name: Start and enable dnsmasq
  service:
    name: dnsmasq
    enabled: yes
    state: started
