---

# PHP is required for Moodle software to run.  Using 7.4 because that is most currently recommended version for Moodle 3.9.3


- name: Make moodle base directory
  file:
    path: "{{ moodle_base_directory }}"
    state: directory

- name: Add apt certificates
  command: apt install -y curl wget gnupg2 ca-certificates lsb-release apt-transport-https
  become: true

#- name: Download GPG key
#  get_url:
#    url: https://packages.sury.org/php/apt.gpg
#    dest: /tmp/apt.gpg
#    mode: '0440'
#
  
#- name: Copy GPG key to /tmp
#  template:
#    src: tmp_apt_gpg.j2
#    dest: /tmp/apt.gpg
#  
#- name: Add apt GPG key
#  command: apt-key add /tmp/apt.gpg
#  become: true
#  
#- name: Update repository that contains PHP 7.4
#  template:
#    src: etc_apt_sources_list_d_php_list.j2
#    dest: /etc/apt/sources.list.d/php.list
#
#- name: Update Apt for Repos
#  apt:
#    update_cache: yes
#

# These are all required by Moodle
- name: Install PHP & Libraries
  apt:
    pkg:
    - php7.3
    - php7.3-cli 
    - php7.3-common 
    - php7.3-curl 
    - php7.3-mbstring
    - php7.3-pgsql 
    - php7.3-xml
    - php7.3-zip
    - php7.3-intl
    - php7.3-xmlrpc
    - php7.3-soap
    - php7.3-fpm
    - php7.3-gd

