---

# PHP is required for Moodle software to run.  Using 7.4 because that is most currently recommended version for Moodle 3.9.3


- name: Make moodle base directory
  file:
    path: "{{ moodle_base_directory }}"
    state: directory

- name: Add apt certificates
  command: apt install -y curl wget gnupg2 ca-certificates lsb-release apt-transport-https
  become: true

# Pi does not require this -- but other OS do so we are ignoring the error.  The install will fail if PHP 7.3 is not found
- name: Add sury apt key  -- This may fail on Pi but error ignored is ok as long as PHP install completes below
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  ignore_errors: yes

- name: Add sury repo into sources list -- This may fail on Pi but error ignored is ok as long as PHP install completes below
  ansible.builtin.apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    state: present
  ignore_errors: yes

# These are all required by Moodle
- name: Install PHP & Libraries
  apt:
    pkg:
    - php7.3
    - php7.3-cli 
    - php7.3-common 
    - php7.3-curl 
    - php7.3-mbstring
    - php7.3-pgsql 
    - php7.3-xml
    - php7.3-zip
    - php7.3-intl
    - php7.3-xmlrpc
    - php7.3-soap
    - php7.3-fpm
    - php7.3-gd

