---
- name: Reset Regulatory Domain
  lineinfile:
    path: /etc/hostapd/hostapd.conf
    regexp: '^country_code=.*'
    line: country_code=00

# In preparation for purging packages in the next step...
# Some packages have lite versions that can be subbed in
#  place of the heavier versions that are commonly used
- name: Install misc dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim-tiny
    - console-setup-mini

# Purge everything we don't actually need to run the ConnectBox
# This includes some of the packages that we needed for the
#  ansible run, but won't need later (ex: git). This saves
#  a significant amount of space in the actual images.

- name: Purge misc armbian utils
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - armbian-config

- name: Purge dev tools and libraries
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - autoconf
    - automake
    - autotools-dev
    - build-essential
    - bison
    - cpp
    - cpp-5
    - dpkg-dev
    - g++
    - g++-5
    - gcc
    - gcc-5
    - git
    - git-man
    - libasan2
    - libbison-dev
    - libc-dev-bin
    - libc6-dev
    - libexpat1-dev
    - libfl-dev
    - libfreetype6-dev
    - libgcc-5-dev
    - libjpeg-dev
    - libjpeg-turbo8-dev
    - libjpeg8-dev
    - libmysqlclient-dev
    - libnl-3-dev
    - libnl-genl-3-dev
    - libpng12-dev
    - libpython3-dev
    - libpython3.5-dev
    - libsigsegv2
    - libssl-dev
    - libstdc++-5-dev
    - libubsan0
    - libwrap0-dev
    - linux-libc-dev
    - make
    - m4
    - patch
    - python3-dev
    - python3.5-dev
    - zlib1g-dev

- name: Purge admin utilities
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - bash-completion
    - command-not-found
    - curl
    - dnsutils
    - dosfstools
    - html2text
    - f3
    - file
    - fping
    - htop
    - iotop
    - man-db
    - screen
    - stress
    - sysbench
    - usbutils
    - vim
    - vim-runtime
    - wget

- name: Purge other packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - alsa-utils
    - bsdmainutils
    - btrfs-tools
    - console-setup
    - debconf-i18n
    - dirmngr
    - fontconfig-config
    - fonts-dejavu-core
    - haveged
    - libasound2
    - libasound2-dat
    - libassuan0
    - libatm1
    - libatomic1
    - libbind9-140
    - libcaca0
    - libcc1-0
    - libdns162
    - libdpkg-perl
    - liberror-perl
    - libfftw3-double3
    - libfreetype6
    - libgd3
    - libgeoip1
    - libgomp1
    - libgpm2
    - libfontconfig1
    - libicu55
    - libisc160
    - libisccc140
    - libisccfg140
    - libisl15
    - libjpeg8
    - libjpeg-turbo8
    - libksba8
    - liblwres141
    - liblzo2-2
    - libmagic1
    - libmpc3
    - libmpfr4
    - libnpth0
    - libperl5.22
    - libpython3.5
    - libsamplerate0
    - libtext-charwidth-perl
    - libtext-iconv-perl
    - libtext-wrapi18n-perl
    - libtiff5
    - libvpx3
    - libx11-6
    - libx11-data
    - libxau6
    - libxcb1
    - libxml2
    - libxpm4
    - libxslt1.1
    - mysql-common
    - ncurses-term
    - perl
    - perl-modules-5.22
    - python-apt
    - python3-command-not-found
    - python3-gdbm
    - python3-gi
    - rcconf
    - toilet
    - toilet-fonts
    - xkb-data

- name: Purge aptitude
  apt:
    state: absent
    autoremove: yes
    purge: yes

- name: Purge apt cache
  file:
    dest: /var/cache/apt
    state: absent

# Schedule a resize of the root partition after the next boot
# This is a benign operation if the partition is already full
#  and scheduling it here allows for it to be expanded on first
#  boot for our images (as long as the device is shutdown and
#  not rebooted after the playbook is run)
# This is deliberately placed after the forced-reboot operations

- name: Schedule a resize of the root partition after the next boot (Armbian)
  service:
    name: resize2fs
    enabled: yes
  when: connectbox_os == "armbian"

- name: Schedule a resize of the root partition after the next boot (Raspbian)
  command: /usr/bin/raspi-config --expand-rootfs
  when: connectbox_os == "raspbian"

# Truncate various log files. We also do this at actual image creation time,
#  but this is a step back to a more cohesive solution

- name: Empty log files
  copy:
    dest: "{{ item.path }}"
    content: ""
    force: yes
    owner: "{{ item.o }}"
    group: "{{ item.g }}"
    mode: "{{ item.p }}"
  with_items:
    - { o: "root", g: "root", p: "0644", path: "/var/log/alternatives.log" }
    - { o: "root", g: "root", p: "0644", path: "/var/log/armhwinfo.log" }
    - { o: "syslog", g: "adm", p: "0640", path: "/var/log/auth.log" }
    - { o: "root", g: "root", p: "0644", path: "/var/log/bootstrap.log" }
    - { o: "root", g: "utmp", p: "0600", path: "/var/log/btmp" }
    - { o: "root", g: "adm", p: "0640", path: "/var/log/dmesg" }
    - { o: "root", g: "root", p: "0644", path: "/var/log/dpkg.log" }
    - { o: "root", g: "root", p: "0644", path: "/var/log/faillog" }
    - { o: "root", g: "root", p: "0640", path: "/var/log/kern.log" }
    - { o: "root", g: "utmp", p: "0664", path: "/var/log/lastlog" }
    - { o: "syslog", g: "adm", p: "0640", path: "/var/log/syslog" }
    - { o: "root", g: "utmp", p: "0664", path: "/var/log/wtmp" }
    - { o: "root", g: "root", p: "0644", path: "/var/log/apt/history.log" }
    - { o: "root", g: "adm", p: "0640", path: "/var/log/apt/term.log" }
    - { o: "www-data", g: "adm", p: "0640", path: "/var/log/nginx/access.log" }
    - { o: "www-data", g: "adm", p: "0640", path: "/var/log/nginx/error.log" }
    - { o: "root", g: "root", p: "0640",
	path: "/var/log/unattended-upgrades/unattended-upgrades-shutdown.log" }

- name: Schedule Final Handlers
  assert:
    that: True
  changed_when: True
  notify:
    - Warn against rebooting
    - Perform final shutdown

