---


- name: Recursively remove existing Moodle directory
  file:
    path: /var/www/moodle/
    state: absent

- name: Make Moodle directory
  file:
    state: directory
    path: /var/www/moodle/
    owner: admin
    group: admin
    mode: 0775
    

- name: Install Moodle 3.9 repo to /var/www/moodle
  git:
    repo: 'https://github.com/RT-coding-team/the-well-moodle.git'
    dest: /var/www/moodle/
    clone: yes
    update: yes

- name: Make moodledata directory
  file:
    state: directory
    path: /var/www/moodledata/
    owner: www-data
    group: www-data
    mode: 0775
    

- name: Copy config.php to working directory
  template:
    src: var_www_moodle_config_php.j2
    dest: /var/www/moodle/config.php

- name: Recursively change ownership /var/www/moodle
  become: true
  file:
    path: /var/www/moodle
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: 0775


# Install generic PHP test script into the moodle directory so we can know that this is ok.    
- name: Copy PHP info.php
  template:
    src: var_www_moodle_info_php.j2
    dest: /var/www/moodle/info.php

