---
- name: Install devmem2 to allow resistor configuration
  apt:
    name: devmem2
    state: present

- name: Make neo battery shutdown virtualenv directory
  file:
    path: "{{ battery_tool_virtualenv_dir }}"
    state: directory

- name: Setup neo battery shutdown virtualenv (python3)
  pip:
    virtualenv: "{{ battery_tool_virtualenv_dir }}"
    virtualenv_python: python3
    editable: False
    name: git+https://github.com/ConnectBox/NEO_BatteryLevelShutdown.git

- name: Copy PA6 pulldown resistor systemd service definition
  template:
    src: "{{ pa6_pulldown_enabler_service_name }}.j2"
    dest: "/etc/systemd/system/{{ pa6_pulldown_enabler_service_name }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart pa6 pulldown service

- name: Copy neo battery shutdown systemd service definition
  template:
    src: "{{ battery_tool_service_name }}.j2"
    dest: "/etc/systemd/system/{{ battery_tool_service_name }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart neo battery shutdown service

# Startup has either already happened, or will happen in the handler
- name: Enable services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
  with_items:
    - "{{ pa6_pulldown_enabler_service_name }}"
    - "{{ battery_tool_service_name }}"
