---

- name: install git for checkout of bible skeleton
  apt:
    name: git
    state: present

- name: install php5-fpm for admin interface
  apt:
    name: php5-fpm
    state: present

- name: Enable php5-fpm
  service:
    name: php5-fpm
    enabled: yes
    state: started

- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "{{ biblebox_default_content_root }}"

- name: Create placeholder index file
  copy:
    dest: "{{ biblebox_default_content_root }}/index.html"
    owner: www-data
    group: www-data
    mode: 0644
    content: |
      <html>
      <head><title>The BibleBox</title></head>
      <body>Placeholder. <a href="/content">content</a> <a href="/admin">admin</a></body>
      </html>

# Permissions are correctly set in the subsequent task
- name: Copy biblebox admin ui
  synchronize:
    src: ../html/admin/
    dest: "{{ biblebox_admin_root }}"

- name: fix ownership of biblebox_default
  file:
    path: "{{ biblebox_admin_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
