---

- name: install git for checkout of bible skeleton
  apt:
    name: git
    state: present

- name: install uwsgi for Python integration
  apt:
    name: uwsgi
    state: present

- name: install uwsgi-python plugin
  apt:
    name: uwsgi-plugin-python
    state: present

- name: install PIP for Python packages
  apt:
    name: python-pip
    state: present

- name: install php5-fpm for admin interface
  apt:
    name: php5-fpm
    state: present

- name: Enable php5-fpm
  service:
    name: php5-fpm
    enabled: yes
    state: started

# commented force=yes given it blows away anything that's in place
#  and it's unclear that we actually want that
- name: checkout biblebox skeleton and deploy as default
  git:
    repo: https://github.com/bbriggs/BibleBox-skeleton.git
    dest: /tmp/BibleBox-skeleton
    depth: 1
    #force=yes

- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "{{ biblebox_default_content_root }}"
    - "{{ biblebox_config_root }}"

- name: move default content into place
  command: rsync -a /tmp/BibleBox-skeleton/content/ {{ biblebox_default_content_root }}

# Trailing slash deliberately absent... we want the shared directory and
#  it's contents in the target directory.
- name: move default shared into place
  command: rsync -a /tmp/BibleBox-skeleton/shared {{ biblebox_default_content_root }}

- name: move default config into place
  command: rsync -a /tmp/BibleBox-skeleton/config/ {{ biblebox_config_root }}

# This makes the config files executable but
# it seems like the only other option is to separately
# set permissions on directory in an additional task
# Since the config files will probably be going away
# I think this is fine for now.
- name: update permissions on biblebox config files
  file:
    dest: "{{ biblebox_config_root }}"
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes

- name: Copy biblebox admin ui
  copy:
    src: ../html/
    dest: "{{ biblebox_default_content_root }}/content/"
    owner: www-data
    group: www-data
    mode: 0644

- name: fix ownership of biblebox_default
  file:
    path: "{{ biblebox_default_content_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: checkout NextCloud integration
  git:
   repo: https://github.com/adavenpo/BibleBox-python-app.git
   dest: "/tmp/BibleBox-nextcloud"
   depth: 1
   #force: yes

- name: Pull python packages
  pip:
    name: webapp2 webob git+https://github.com/owncloud/pyocclient.git
    state: present

- name: deploy NextCloud integration static content
  shell: "cp -a /tmp/BibleBox-nextcloud/static/* {{ biblebox_default_content_root }}"

- name: deploy NextCloud integration WSGI app
  command: "cp -a /tmp/BibleBox-nextcloud/wsgi /var/www/"

- name: Add app link to uwsgi config
  file:
    src: /var/www/wsgi/app.ini
    dest: /etc/uwsgi/apps-enabled/app.ini
    state: link

