---

- name: install git for checkout of bible skeleton
  apt:
    name: git
    state: present

- name: install php5-fpm for admin interface
  apt:
    name: php5-fpm
    state: present

- name: Enable php5-fpm
  service:
    name: php5-fpm
    enabled: yes
    state: started

# commented force=yes given it blows away anything that's in place
#  and it's unclear that we actually want that
- name: checkout biblebox skeleton and deploy as default
  git:
    repo: https://github.com/bbriggs/BibleBox-skeleton.git
    dest: /tmp/BibleBox-skeleton
    depth: 1
    #force=yes

- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "{{ biblebox_default_content_root }}"
    - "{{ biblebox_config_root }}"

- name: move default content into place
  command: rsync -a /tmp/BibleBox-skeleton/content {{ biblebox_default_content_root }}

- name: move default shared into place
  command: rsync -a /tmp/BibleBox-skeleton/shared {{ biblebox_default_content_root }}

# Trailing slash deliberately present... we want the contents of the config
#  directory, but not the directory itself in the target.
- name: move default config into place
  command: rsync -a /tmp/BibleBox-skeleton/config/ {{ biblebox_config_root }}

# This makes the config files executable but
# it seems like the only other option is to separately
# set permissions on directory in an additional task
# Since the config files will probably be going away
# I think this is fine for now.
- name: update permissions on biblebox config files
  file:
    dest: "{{ biblebox_config_root }}"
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes

- name: Copy biblebox admin ui
  copy:
    src: ../html/
    dest: "{{ biblebox_default_content_root }}/content/"
    owner: www-data
    group: www-data
    mode: 0644

- name: fix ownership of biblebox_default
  file:
    path: "{{ biblebox_default_content_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
