---

- name: install git for checkout of default content
  apt:
    name: git
    state: present

- name: install php5-fpm for admin interface
  apt:
    name: php5-fpm
    state: present

- name: Enable php5-fpm
  service:
    name: php5-fpm
    enabled: yes
    state: started

- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "{{ connectbox_default_content_root }}"

# Copy client interface files
- name: Copy connectbox client interface
  synchronize:
    src: ../html/client/
    dest: "{{ connectbox_default_content_root }}"

- name: Copy iOS captive portal response page
  copy:
    src: success.html
    dest: "{{ connectbox_default_content_root }}"

# Permissions are correctly set in the subsequent task
- name: Copy connectbox admin ui
  synchronize:
    src: ../html/admin/
    dest: "{{ connectbox_admin_root }}"

- name: fix ownership of connectbox_web_root
  file:
    path: "{{ connectbox_web_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
