---
# If the system is updated before any iptables modules are loaded
#  the system can't find the modules and iptables rules can't be
#  loaded first time. (A repeat ansible run seems to fix it, though).
# Let's avoid a first-time failure by doing the upgrade after the
#  iptables rules have been updated.
# Consistent with: https://serverfault.com/questions/593263/iptables-nat-does-not-exist
- name: Update existing packages
  apt:
    upgrade: safe
- name: install git
  apt: pkg=git state=installed update_cache=true
- name: install php5-fpm
  apt: pkg=php5-fpm state=installed update_cache=true
- name: allow www-data to pumount
  blockinfile:
    dest: /etc/sudoers
    block: |
      www-data ALL=(ALL) ALL
      www-data ALL=(ALL) NOPASSWD: /usr/bin/pumount
- name: checkout biblebox skeleton and deploy as default
  git: repo=https://github.com/bbriggs/BibleBox-skeleton.git
       dest=/tmp/BibleBox-skeleton
       depth=1
       force=yes
- name: create folders for default content/shared
  file: path=/var/www/biblebox/biblebox_default state=directory owner=www-data group=www-data mode=0775 recurse=yes
- name: create folder for config
  file: path=/etc/biblebox/ state=directory owner=www-data group=www-data mode=0775 recurse=yes
- name: move default content into place
  command: cp -r /tmp/BibleBox-skeleton/content /var/www/biblebox/biblebox_default
- name: move default shared into place
  command: cp -r /tmp/BibleBox-skeleton/shared /var/www/biblebox/biblebox_default
- name: move default config into place
  shell: "cp -r /tmp/BibleBox-skeleton/config/* /etc/biblebox"
- name: checkout biblebox php admin interface
  git: repo=https://github.com/stevish-com/bibleboxpi-interface.git
       dest=/var/www/biblebox/biblebox_default/content/admin/
       depth=1
       force=yes
- name: fix ownership of biblebox_default
  file: path=/var/www/biblebox/biblebox_default state=directory owner=www-data group=www-data mode=0775 recurse=yes
