---

# For RPi modules (these have internal wifi)
# Use selected client_facing_if specified wlan in two files

- name: update cli.py
  replace:
    path: /usr/local/waypoint/wifi_configurator_venv/lib/python3.7/site-packages/wifi_configurator/cli.py
    regexp: 'wlan0'
    replace: '{{ client_facing_if }}'
  when: waypoint_os == "raspbian"

- name: update WayPointBoxManage.sh
  replace:
    path: /usr/local/waypoint/bin/WayPointBoxManage.sh
    regexp: 'wlan0'
    replace: '{{ client_facing_if }}'
  when: waypoint_os == "raspbian"

